language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  -
  - NO_DEFAULT_FEATURES=1

script:
  - if [ "$NO_DEFAULT_FEATURES" = "1" ]; then NO_DEFAULT_FEATURES="--no-default-features"; else NO_DEFAULT_FEATURES=""; fi
  - cargo test --verbose $NO_DEFAULT_FEATURES --features "$FEATURES"

matrix:
  include:
    - rust: stable
      os: linux
      env: TARGET=x86_64-unknown-linux-musl
      install: rustup target add $TARGET
      script: cargo test --target $TARGET
    - rust: beta
      os: linux
      env: TARGET=x86_64-unknown-linux-musl
      install: rustup target add $TARGET
      script: cargo test --target $TARGET
    - rust: nightly
      os: linux
      env: TARGET=x86_64-unknown-linux-musl
      install: rustup target add $TARGET
      script: cargo test --target $TARGET
    - rust: stable
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      install:
        - rustup set default-host $TARGET
        - rustup default $TRAVIS_RUST_VERSION
        - rustup target add $TARGET
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "x86_64-w64-mingw32-gcc"\nar = "x86_64-w64-mingw32-ar"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET
    - rust: beta
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      install:
        - rustup set default-host $TARGET
        - rustup default $TRAVIS_RUST_VERSION
        - rustup target add $TARGET
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "x86_64-w64-mingw32-gcc"\nar = "x86_64-w64-mingw32-ar"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET
    - rust: nightly
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      install:
        - rustup set default-host $TARGET
        - rustup default $TRAVIS_RUST_VERSION
        - rustup target add $TARGET
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "x86_64-w64-mingw32-gcc"\nar = "x86_64-w64-mingw32-ar"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET